### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [arkup/juniEmu#1]
sorry for the late reply, and thanks for informing about this nice project!

updated our showcases with JuniEmu at http://www.capstone-engine.org/showcase.html & http://www.unicorn-engine.org/showcase/

keep it up, cheers!

**Comment by aquynh** [comment]
btw your project description is still empty: "No description or website provided."

cheers.

**Comment by arkup** [comment]
Thx, I've added description. Again thank you for your work on Capstone and Unicorn awesome projects.
